version: 2

sources:
  - name: snowflake_sample_data
    description: 'Sample data from snowflake sample'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
      
